### ISSUE TITLE
[Bug] The survey item content on the Home screen is difficult to see and doesn't match with the design

### ISSUE THREAD

**Issue by minhnimble** [hsu-hsu/nimble-survey-app#17]
## Issue

The application needs to show the survey list after loading all the data with a valid logged-in session-like design. Currently, there are multiple UI problems with a survey item on the Home screen:

- The display image for each survey item is very blurry.
- The `Today` and date texts are not shown as per the design.
- The default avatar icon doesn't show as per the design.
- The left indentation between the survey title, description and the page indicator isn't properly aligned per design.
- The page indicator UI doesn't match with the design.

Example screenshot:
  <img src="https://github.com/hsu-hsu/nimble-survey-app/assets/70877098/06daca59-d87b-478c-ab43-94215eed0ef4" width="300">

## Expect

The survey item should look clearer and identical to the design:
  <img src="https://user-images.githubusercontent.com/70877098/159682538-5934d10f-fd97-4c01-b95a-28b0c6199ed8.png" width="300">

**Comment by hsu-hsu** [comment]
In this pull request, I add today text, today date and avatar image in home screen as design. I also fixed pager indicator design and align the left margin of textview and pager indicator as design. 

For the display blurry bug, I think there is a problem between the aspect ratios of the image we received from api and the one we want to display. For the full image design, I used centercrop in scale type. That is the reason image is blurry. If we use fitcenter in scale type, the image will be more clear but it won't be full screen. I only set scale type to centercrop in this pull request because if we can get the desired aspect ratio, it will be the best option for this kind of display.

pull request -> #25

**Comment by minhnimble** [comment]
> For the display blurry bug, I think there is a problem between the aspect ratios of the image we received from api and the one we want to display.

Hi @hsu-hsu, just sharing [here](https://documenter.getpostman.com/view/11835486/UVsPNPfU#064357a5-4625-4ef7-b042-0d1f7e2f2acb) again in case you miss, the API can support high res images with instructions from Postman. 😁

**Comment by hsu-hsu** [comment]
Hello Mike,

Thank you for your information. I oversee that one while reading API documentation😅. I will replace image with high resolution image in the home screen.

**Comment by hsu-hsu** [comment]
In this pull request, I fix image blurry bug in home screen.
pull request -> #28
